spring:
  datasourse:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #jpa 설정
    hibernate:
      ddl-auto: create #자동 테이블 생성
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #실행 한 쿼리 로깅해줌
    # o줌g.hibernate.type: trace #스프링 부트 2.x, hibernate5
    # org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6